/*  XBSX2 - PS2 Emulator for Xbox Consoles
 *  Copyright (C) 2002-2021  PCSX2 Dev Team
 * 
 *  XBSX2 is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU Lesser General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  XBSX2 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with XBSX2.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// We abuse the preprocessor here to only need to specify function names once.
// Function names are prefixed so to not conflict with system symbols at runtime.
#define VULKAN_MODULE_ENTRY_POINT(name, required) extern PFN_##name xbsx2_##name;
#define VULKAN_INSTANCE_ENTRY_POINT(name, required) extern PFN_##name xbsx2_##name;
#define VULKAN_DEVICE_ENTRY_POINT(name, required) extern PFN_##name xbsx2_##name;
#define VULKAN_DEFINE_NAME_PREFIX xbsx2_
#include "EntryPoints.inl"
#undef VULKAN_DEFINE_NAME_PREFIX
#undef VULKAN_DEVICE_ENTRY_POINT
#undef VULKAN_INSTANCE_ENTRY_POINT
#undef VULKAN_MODULE_ENTRY_POINT

#ifdef __cplusplus
}
#endif

#define vkCreateInstance xbsx2_vkCreateInstance
#define vkGetInstanceProcAddr xbsx2_vkGetInstanceProcAddr
#define vkEnumerateInstanceExtensionProperties xbsx2_vkEnumerateInstanceExtensionProperties
#define vkEnumerateInstanceLayerProperties xbsx2_vkEnumerateInstanceLayerProperties
#define vkEnumerateInstanceVersion xbsx2_vkEnumerateInstanceVersion

#define vkGetDeviceProcAddr xbsx2_vkGetDeviceProcAddr
#define vkDestroyInstance xbsx2_vkDestroyInstance
#define vkEnumeratePhysicalDevices xbsx2_vkEnumeratePhysicalDevices
#define vkGetPhysicalDeviceFeatures xbsx2_vkGetPhysicalDeviceFeatures
#define vkGetPhysicalDeviceFormatProperties xbsx2_vkGetPhysicalDeviceFormatProperties
#define vkGetPhysicalDeviceImageFormatProperties xbsx2_vkGetPhysicalDeviceImageFormatProperties
#define vkGetPhysicalDeviceProperties xbsx2_vkGetPhysicalDeviceProperties
#define vkGetPhysicalDeviceQueueFamilyProperties xbsx2_vkGetPhysicalDeviceQueueFamilyProperties
#define vkGetPhysicalDeviceMemoryProperties xbsx2_vkGetPhysicalDeviceMemoryProperties
#define vkCreateDevice xbsx2_vkCreateDevice
#define vkEnumerateDeviceExtensionProperties xbsx2_vkEnumerateDeviceExtensionProperties
#define vkEnumerateDeviceLayerProperties xbsx2_vkEnumerateDeviceLayerProperties
#define vkGetPhysicalDeviceSparseImageFormatProperties xbsx2_vkGetPhysicalDeviceSparseImageFormatProperties
#define vkDestroySurfaceKHR xbsx2_vkDestroySurfaceKHR
#define vkGetPhysicalDeviceSurfaceSupportKHR xbsx2_vkGetPhysicalDeviceSurfaceSupportKHR
#define vkGetPhysicalDeviceSurfaceCapabilitiesKHR xbsx2_vkGetPhysicalDeviceSurfaceCapabilitiesKHR
#define vkGetPhysicalDeviceSurfaceFormatsKHR xbsx2_vkGetPhysicalDeviceSurfaceFormatsKHR
#define vkGetPhysicalDeviceSurfacePresentModesKHR xbsx2_vkGetPhysicalDeviceSurfacePresentModesKHR
#define vkCreateWin32SurfaceKHR xbsx2_vkCreateWin32SurfaceKHR
#define vkGetPhysicalDeviceWin32PresentationSupportKHR xbsx2_vkGetPhysicalDeviceWin32PresentationSupportKHR
#define vkCreateXlibSurfaceKHR xbsx2_vkCreateXlibSurfaceKHR
#define vkGetPhysicalDeviceXlibPresentationSupportKHR xbsx2_vkGetPhysicalDeviceXlibPresentationSupportKHR
#define vkCreateWaylandSurfaceKHR xbsx2_vkCreateWaylandSurfaceKHR
#define vkCreateAndroidSurfaceKHR xbsx2_vkCreateAndroidSurfaceKHR
#define vkCreateMacOSSurfaceMVK xbsx2_vkCreateMacOSSurfaceMVK
#define vkCreateMetalSurfaceEXT xbsx2_vkCreateMetalSurfaceEXT

// VK_EXT_debug_utils
#define vkCmdBeginDebugUtilsLabelEXT xbsx2_vkCmdBeginDebugUtilsLabelEXT
#define vkCmdEndDebugUtilsLabelEXT xbsx2_vkCmdEndDebugUtilsLabelEXT
#define vkCmdInsertDebugUtilsLabelEXT xbsx2_vkCmdInsertDebugUtilsLabelEXT
#define vkCreateDebugUtilsMessengerEXT xbsx2_vkCreateDebugUtilsMessengerEXT
#define vkDestroyDebugUtilsMessengerEXT xbsx2_vkDestroyDebugUtilsMessengerEXT
#define vkQueueBeginDebugUtilsLabelEXT xbsx2_vkQueueBeginDebugUtilsLabelEXT
#define vkQueueEndDebugUtilsLabelEXT xbsx2_vkQueueEndDebugUtilsLabelEXT
#define vkQueueInsertDebugUtilsLabelEXT xbsx2_vkQueueInsertDebugUtilsLabelEXT
#define vkSetDebugUtilsObjectNameEXT xbsx2_vkSetDebugUtilsObjectNameEXT
#define vkSetDebugUtilsObjectTagEXT xbsx2_vkSetDebugUtilsObjectTagEXT
#define vkSubmitDebugUtilsMessageEXT xbsx2_vkSubmitDebugUtilsMessageEXT

#define vkGetPhysicalDeviceSurfaceCapabilities2KHR xbsx2_vkGetPhysicalDeviceSurfaceCapabilities2KHR
#define vkGetPhysicalDeviceDisplayPropertiesKHR xbsx2_vkGetPhysicalDeviceDisplayPropertiesKHR
#define vkGetPhysicalDeviceDisplayPlanePropertiesKHR xbsx2_vkGetPhysicalDeviceDisplayPlanePropertiesKHR
#define vkGetDisplayPlaneSupportedDisplaysKHR xbsx2_vkGetDisplayPlaneSupportedDisplaysKHR
#define vkGetDisplayModePropertiesKHR xbsx2_vkGetDisplayModePropertiesKHR
#define vkCreateDisplayModeKHR xbsx2_vkCreateDisplayModeKHR
#define vkGetDisplayPlaneCapabilitiesKHR xbsx2_vkGetDisplayPlaneCapabilitiesKHR
#define vkCreateDisplayPlaneSurfaceKHR xbsx2_vkCreateDisplayPlaneSurfaceKHR

// Vulkan 1.1 functions.
#define vkGetPhysicalDeviceFeatures2 xbsx2_vkGetPhysicalDeviceFeatures2
#define vkGetPhysicalDeviceProperties2 xbsx2_vkGetPhysicalDeviceProperties2
#define vkGetPhysicalDeviceMemoryProperties2 xbsx2_vkGetPhysicalDeviceMemoryProperties2

#define vkDestroyDevice xbsx2_vkDestroyDevice
#define vkGetDeviceQueue xbsx2_vkGetDeviceQueue
#define vkQueueSubmit xbsx2_vkQueueSubmit
#define vkQueueWaitIdle xbsx2_vkQueueWaitIdle
#define vkDeviceWaitIdle xbsx2_vkDeviceWaitIdle
#define vkAllocateMemory xbsx2_vkAllocateMemory
#define vkFreeMemory xbsx2_vkFreeMemory
#define vkMapMemory xbsx2_vkMapMemory
#define vkUnmapMemory xbsx2_vkUnmapMemory
#define vkFlushMappedMemoryRanges xbsx2_vkFlushMappedMemoryRanges
#define vkInvalidateMappedMemoryRanges xbsx2_vkInvalidateMappedMemoryRanges
#define vkGetDeviceMemoryCommitment xbsx2_vkGetDeviceMemoryCommitment
#define vkBindBufferMemory xbsx2_vkBindBufferMemory
#define vkBindImageMemory xbsx2_vkBindImageMemory
#define vkGetBufferMemoryRequirements xbsx2_vkGetBufferMemoryRequirements
#define vkGetImageMemoryRequirements xbsx2_vkGetImageMemoryRequirements
#define vkGetImageSparseMemoryRequirements xbsx2_vkGetImageSparseMemoryRequirements
#define vkQueueBindSparse xbsx2_vkQueueBindSparse
#define vkCreateFence xbsx2_vkCreateFence
#define vkDestroyFence xbsx2_vkDestroyFence
#define vkResetFences xbsx2_vkResetFences
#define vkGetFenceStatus xbsx2_vkGetFenceStatus
#define vkWaitForFences xbsx2_vkWaitForFences
#define vkCreateSemaphore xbsx2_vkCreateSemaphore
#define vkDestroySemaphore xbsx2_vkDestroySemaphore
#define vkCreateEvent xbsx2_vkCreateEvent
#define vkDestroyEvent xbsx2_vkDestroyEvent
#define vkGetEventStatus xbsx2_vkGetEventStatus
#define vkSetEvent xbsx2_vkSetEvent
#define vkResetEvent xbsx2_vkResetEvent
#define vkCreateQueryPool xbsx2_vkCreateQueryPool
#define vkDestroyQueryPool xbsx2_vkDestroyQueryPool
#define vkGetQueryPoolResults xbsx2_vkGetQueryPoolResults
#define vkCreateBuffer xbsx2_vkCreateBuffer
#define vkDestroyBuffer xbsx2_vkDestroyBuffer
#define vkCreateBufferView xbsx2_vkCreateBufferView
#define vkDestroyBufferView xbsx2_vkDestroyBufferView
#define vkCreateImage xbsx2_vkCreateImage
#define vkDestroyImage xbsx2_vkDestroyImage
#define vkGetImageSubresourceLayout xbsx2_vkGetImageSubresourceLayout
#define vkCreateImageView xbsx2_vkCreateImageView
#define vkDestroyImageView xbsx2_vkDestroyImageView
#define vkCreateShaderModule xbsx2_vkCreateShaderModule
#define vkDestroyShaderModule xbsx2_vkDestroyShaderModule
#define vkCreatePipelineCache xbsx2_vkCreatePipelineCache
#define vkDestroyPipelineCache xbsx2_vkDestroyPipelineCache
#define vkGetPipelineCacheData xbsx2_vkGetPipelineCacheData
#define vkMergePipelineCaches xbsx2_vkMergePipelineCaches
#define vkCreateGraphicsPipelines xbsx2_vkCreateGraphicsPipelines
#define vkCreateComputePipelines xbsx2_vkCreateComputePipelines
#define vkDestroyPipeline xbsx2_vkDestroyPipeline
#define vkCreatePipelineLayout xbsx2_vkCreatePipelineLayout
#define vkDestroyPipelineLayout xbsx2_vkDestroyPipelineLayout
#define vkCreateSampler xbsx2_vkCreateSampler
#define vkDestroySampler xbsx2_vkDestroySampler
#define vkCreateDescriptorSetLayout xbsx2_vkCreateDescriptorSetLayout
#define vkDestroyDescriptorSetLayout xbsx2_vkDestroyDescriptorSetLayout
#define vkCreateDescriptorPool xbsx2_vkCreateDescriptorPool
#define vkDestroyDescriptorPool xbsx2_vkDestroyDescriptorPool
#define vkResetDescriptorPool xbsx2_vkResetDescriptorPool
#define vkAllocateDescriptorSets xbsx2_vkAllocateDescriptorSets
#define vkFreeDescriptorSets xbsx2_vkFreeDescriptorSets
#define vkUpdateDescriptorSets xbsx2_vkUpdateDescriptorSets
#define vkCreateFramebuffer xbsx2_vkCreateFramebuffer
#define vkDestroyFramebuffer xbsx2_vkDestroyFramebuffer
#define vkCreateRenderPass xbsx2_vkCreateRenderPass
#define vkDestroyRenderPass xbsx2_vkDestroyRenderPass
#define vkGetRenderAreaGranularity xbsx2_vkGetRenderAreaGranularity
#define vkCreateCommandPool xbsx2_vkCreateCommandPool
#define vkDestroyCommandPool xbsx2_vkDestroyCommandPool
#define vkResetCommandPool xbsx2_vkResetCommandPool
#define vkAllocateCommandBuffers xbsx2_vkAllocateCommandBuffers
#define vkFreeCommandBuffers xbsx2_vkFreeCommandBuffers
#define vkBeginCommandBuffer xbsx2_vkBeginCommandBuffer
#define vkEndCommandBuffer xbsx2_vkEndCommandBuffer
#define vkResetCommandBuffer xbsx2_vkResetCommandBuffer
#define vkCmdBindPipeline xbsx2_vkCmdBindPipeline
#define vkCmdSetViewport xbsx2_vkCmdSetViewport
#define vkCmdSetScissor xbsx2_vkCmdSetScissor
#define vkCmdSetLineWidth xbsx2_vkCmdSetLineWidth
#define vkCmdSetDepthBias xbsx2_vkCmdSetDepthBias
#define vkCmdSetBlendConstants xbsx2_vkCmdSetBlendConstants
#define vkCmdSetDepthBounds xbsx2_vkCmdSetDepthBounds
#define vkCmdSetStencilCompareMask xbsx2_vkCmdSetStencilCompareMask
#define vkCmdSetStencilWriteMask xbsx2_vkCmdSetStencilWriteMask
#define vkCmdSetStencilReference xbsx2_vkCmdSetStencilReference
#define vkCmdBindDescriptorSets xbsx2_vkCmdBindDescriptorSets
#define vkCmdBindIndexBuffer xbsx2_vkCmdBindIndexBuffer
#define vkCmdBindVertexBuffers xbsx2_vkCmdBindVertexBuffers
#define vkCmdDraw xbsx2_vkCmdDraw
#define vkCmdDrawIndexed xbsx2_vkCmdDrawIndexed
#define vkCmdDrawIndirect xbsx2_vkCmdDrawIndirect
#define vkCmdDrawIndexedIndirect xbsx2_vkCmdDrawIndexedIndirect
#define vkCmdDispatch xbsx2_vkCmdDispatch
#define vkCmdDispatchIndirect xbsx2_vkCmdDispatchIndirect
#define vkCmdCopyBuffer xbsx2_vkCmdCopyBuffer
#define vkCmdCopyImage xbsx2_vkCmdCopyImage
#define vkCmdBlitImage xbsx2_vkCmdBlitImage
#define vkCmdCopyBufferToImage xbsx2_vkCmdCopyBufferToImage
#define vkCmdCopyImageToBuffer xbsx2_vkCmdCopyImageToBuffer
#define vkCmdUpdateBuffer xbsx2_vkCmdUpdateBuffer
#define vkCmdFillBuffer xbsx2_vkCmdFillBuffer
#define vkCmdClearColorImage xbsx2_vkCmdClearColorImage
#define vkCmdClearDepthStencilImage xbsx2_vkCmdClearDepthStencilImage
#define vkCmdClearAttachments xbsx2_vkCmdClearAttachments
#define vkCmdResolveImage xbsx2_vkCmdResolveImage
#define vkCmdSetEvent xbsx2_vkCmdSetEvent
#define vkCmdResetEvent xbsx2_vkCmdResetEvent
#define vkCmdWaitEvents xbsx2_vkCmdWaitEvents
#define vkCmdPipelineBarrier xbsx2_vkCmdPipelineBarrier
#define vkCmdBeginQuery xbsx2_vkCmdBeginQuery
#define vkCmdEndQuery xbsx2_vkCmdEndQuery
#define vkCmdResetQueryPool xbsx2_vkCmdResetQueryPool
#define vkCmdWriteTimestamp xbsx2_vkCmdWriteTimestamp
#define vkCmdCopyQueryPoolResults xbsx2_vkCmdCopyQueryPoolResults
#define vkCmdPushConstants xbsx2_vkCmdPushConstants
#define vkCmdBeginRenderPass xbsx2_vkCmdBeginRenderPass
#define vkCmdNextSubpass xbsx2_vkCmdNextSubpass
#define vkCmdEndRenderPass xbsx2_vkCmdEndRenderPass
#define vkCmdExecuteCommands xbsx2_vkCmdExecuteCommands
#define vkCreateSwapchainKHR xbsx2_vkCreateSwapchainKHR
#define vkDestroySwapchainKHR xbsx2_vkDestroySwapchainKHR
#define vkGetSwapchainImagesKHR xbsx2_vkGetSwapchainImagesKHR
#define vkAcquireNextImageKHR xbsx2_vkAcquireNextImageKHR
#define vkQueuePresentKHR xbsx2_vkQueuePresentKHR

// Vulkan 1.1 functions.
#define vkGetBufferMemoryRequirements2 xbsx2_vkGetBufferMemoryRequirements2
#define vkGetImageMemoryRequirements2 xbsx2_vkGetImageMemoryRequirements2
#define vkBindBufferMemory2 xbsx2_vkBindBufferMemory2
#define vkBindImageMemory2 xbsx2_vkBindImageMemory2

#ifdef SUPPORTS_VULKAN_EXCLUSIVE_FULLSCREEN
#define vkAcquireFullScreenExclusiveModeEXT xbsx2_vkAcquireFullScreenExclusiveModeEXT
#define vkReleaseFullScreenExclusiveModeEXT xbsx2_vkReleaseFullScreenExclusiveModeEXT
#endif
